/**
 * Add Scenes to work with the app scene manager
 */

ADD_SCENE(app, menu, main_menu)
ADD_SCENE(app, sniffing, sniffing_option)
ADD_SCENE(app, box_sniffing, box_sniffing)
ADD_SCENE(app, device_no_connected, device_no_connected)

ADD_SCENE(app, sender, sender_option)
ADD_SCENE(app, set_timing, set_timing_option)
ADD_SCENE(app, set_data_sender, set_data_sender_option)
ADD_SCENE(app, send_message, send_message_option)
ADD_SCENE(app, input_data, input_data_option)
ADD_SCENE(app, settings, settings_option)
ADD_SCENE(app, wiring, wiring_option)

ADD_SCENE(app, uds_menu, uds_menu_option)
ADD_SCENE(app, uds_session_select, uds_session_select_option)
ADD_SCENE(app, uds_single_frame_request_sender, uds_single_frame_request_sender_option)
ADD_SCENE(app, uds_single_frame_request_response, uds_single_frame_request_response_option)
ADD_SCENE(app, uds_single_frame_data, uds_single_frame_data_option)
ADD_SCENE(app, uds_request_vin, uds_request_vin_option)
ADD_SCENE(app, uds_set_diagnostic_session, uds_set_diagnostic_session_option)
ADD_SCENE(app, uds_set_session_response, uds_set_session_response)
ADD_SCENE(app, uds_ecu_reset, uds_ecu_reset_option)
ADD_SCENE(app, uds_ecu_reset_response, uds_ecu_reset_response_option)
ADD_SCENE(app, uds_get_dtc_menu, uds_get_dtc_menu_option)
ADD_SCENE(app, uds_dtc_response, uds_dtc_response_option)
ADD_SCENE(app, uds_settings, uds_settings_option)
ADD_SCENE(app, uds_set_ids, uds_set_ids_option)
ADD_SCENE(app, uds_discovery_settings, uds_discovery_settings_option)
ADD_SCENE(app, uds_ecu_discovery, uds_ecu_discovery_option)
ADD_SCENE(app, uds_allinone, uds_allinone_option)
ADD_SCENE(app, uds_allinone_settings, uds_allinone_settings_option)
ADD_SCENE(app, uds_allinone_run, uds_allinone_run_option)
ADD_SCENE(app, uds_service_scan, uds_service_scan_option)
ADD_SCENE(app, uds_tester_present, uds_tester_present_option)
ADD_SCENE(app, uds_security_seed_menu, uds_security_seed_menu_option)
ADD_SCENE(app, uds_security_seed_result, uds_security_seed_result_option)
ADD_SCENE(app, uds_did_scan_menu, uds_did_scan_menu_option)
ADD_SCENE(app, uds_did_scan_result, uds_did_scan_result_option)
ADD_SCENE(app, uds_bruteforce_menu, uds_bruteforce_menu_option)
ADD_SCENE(app, uds_bruteforce_result, uds_bruteforce_result_option)
